[package]
name = "age"
description = "[BETA] A simple, secure, and modern encryption tool."
version = "0.1.1"
authors = ["Jack Grigg <thestr4d@gmail.com>"]
repository = "https://github.com/str4d/rage"
readme = "README.md"
keywords = ["rage", "cli", "encryption"]
categories = ["command-line-utilities", "cryptography"]
license = "MIT OR Apache-2.0"
edition = "2018"
default-run = "rage"

[package.metadata.deb]
name = "rage"
extended-description = """\
age is a simple, secure and modern encryption format with small explicit keys, \
no config options, and UNIX-style composability. rage is a Rust implementation \
of the age specification."""
section = "utils"
assets = [
    ["target/rage.1.gz", "usr/share/man/man1/", "644"],
    ["target/rage-keygen.1.gz", "usr/share/man/man1/", "644"],
    ["target/rage-mount.1.gz", "usr/share/man/man1/", "644"],
    ["target/release/rage", "usr/bin/", "755"],
    ["target/release/rage-keygen", "usr/bin/", "755"],
    ["target/release/rage-mount", "usr/bin/", "755"],
    ["README.md", "usr/share/doc/rage/README.md", "644"],
]
features = ["mount"]

[badges]
maintenance = { status = "experimental" }

[dependencies]
#
# Library dependencies
#

# Dependencies required by the age specification:
# - Base64 from RFC 4648
base64 = "0.10"

# - ChaCha20-Poly1305 from RFC 7539
chacha20poly1305 = "0.1"

# - X25519 from RFC 7748
x25519-dalek = "0.6"

# - HKDF from RFC 5869 with SHA-256
# - HMAC from RFC 2104 with SHA-256
hkdf = "0.8"
hmac = "0.7"
sha2 = "0.8"

# - scrypt from RFC 7914
scrypt = { version = "0.2", default-features = false }

# - secp256r1
elliptic-curve = "0.2"
ring = "0.16.9"

# - CSPRNG
rand = "0.7"

# - Key encoding
bech32 = "0.7"

# OpenSSH-specific dependencies:
# - RSAES-OAEP from RFC 8017 with SHA-256 and MGF1 (behind unstable feature flag)
num-traits = { version = "0.2", optional = true }
rsa = { version = "0.2", git = "https://github.com/str4d/RSA", branch = "oaep", optional = true }

# - Conversion of public keys from Ed25519 to X25519
curve25519-dalek = "2"

# - Encrypted keys
aes-ctr = "0.3"
bcrypt-pbkdf = "0.1"

# Parsing
cookie-factory = "0.3"
nom = "5"

# Armor writing
radix64 = "0.6"

# Secret management
secrecy = "0.5"
zeroize = "1"

#
# Tool dependencies
#

# Common CLI dependencies
dialoguer = { version = "0.4", optional = true }
dirs = { version = "2", optional = true }
gumdrop = { version = "0.6", optional = true }
log = { version = "0.4", optional = true }

# rage and rage-keygen dependencies
chrono = { version = "0.4", optional = true }
console = { version = "0.9", optional = true }
minreq = { version = "1.4", features = ["https"], optional = true }

# rage-mount dependencies
env_logger = { version = "0.7", optional = true }
fuse_mt = { version = "0.5", optional = true }
libc = { version = "0.2", optional = true }
tar = { version = "0.4", optional = true }
time = { version = "0.1", optional = true }
zip = { version = "0.5", optional = true }

[dev-dependencies]
flate2 = "1"
man = "0.3"
quickcheck = "0.8"
quickcheck_macros = "0.8"

[features]
default = ["cli"]
cli-common = ["dialoguer", "dirs", "gumdrop", "log"]
cli = ["cli-common", "chrono", "console", "env_logger", "minreq"]
mount = ["cli-common", "env_logger", "fuse_mt", "libc", "tar", "time", "zip"]
unstable = ["num-traits", "rsa"]

[[bin]]
name = "rage-mount"
required-features = ["mount"]
