name: Build binaries and publish release

on: push

jobs:
  build:
    name: Build for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, armv7, arm64, windows, macos]
        include:
          - name: linux
            os: ubuntu-latest
            build_deps: >
              libfuse-dev
              libpcsclite-dev
            build_flags: --features mount
            archive_name: rage.tar.gz
            asset_suffix: x86_64-linux.tar.gz

          - name: armv7
            os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            build_deps: >
              gcc-arm-linux-gnueabihf
            cargo_config: |
              [target.armv7-unknown-linux-gnueabihf]
              linker = "arm-linux-gnueabihf-gcc"
            build_flags: --target armv7-unknown-linux-gnueabihf
            archive_name: rage.tar.gz
            asset_suffix: armv7-linux.tar.gz

          - name: arm64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            build_deps: >
              gcc-aarch64-linux-gnu
            cargo_config: |
              [target.aarch64-unknown-linux-gnu]
              linker = "aarch64-linux-gnu-gcc"
            build_flags: --target aarch64-unknown-linux-gnu
            archive_name: rage.tar.gz
            asset_suffix: arm64-linux.tar.gz

          - name: windows
            os: windows-latest
            archive_name: rage.zip
            asset_suffix: x86_64-windows.zip

          - name: macos
            os: macos-latest
            archive_name: rage.tar.gz
            asset_suffix: x86_64-darwin.tar.gz

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.37.0
          override: true
      
      - name: Test version
        run: echo ${{steps.get_version.outputs.VERSION}}
        shell: bash

      - name: Add target
        run: rustup target add ${{ matrix.target }}
        if: matrix.target != ''

      - name: Install linux build dependencies
        run: sudo apt update && sudo apt install ${{ matrix.build_deps }}
        if: matrix.build_deps != ''

      - name: Set up .cargo/config
        run: |
          mkdir .cargo
          echo '${{ matrix.cargo_config }}' >.cargo/config
        if: matrix.cargo_config != ''

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all --release --locked ${{ matrix.build_flags }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
        shell: bash

      - name: Create archive
        run: |
          mkdir -p release/rage
          mv target/${{ matrix.target }}/release/rage* release/rage/
          rm release/rage/*.d
          tar czf ${{ matrix.archive_name }} -C release/ rage/
        if: (matrix.name != 'windows' && startsWith(steps.get_version.outputs.VERSION ,'v'))

      - name: Create archive [Windows]
        run: |
          mkdir -p release/rage
          mv target/release/rage.exe release/rage/
          mv target/release/rage-keygen.exe release/rage/
          cd release/
          7z.exe a ../${{ matrix.archive_name }} rage/
        shell: bash
        if: (matrix.name == 'windows' && startsWith(steps.get_version.outputs.VERSION ,'v'))

      - name: Upload archive to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.archive_name }}
          asset_name: rage-${{ steps.get_version.outputs.VERSION }}-${{ matrix.asset_suffix }}
          tag: ${{ github.ref }}
        if: (startsWith(steps.get_version.outputs.VERSION ,'v'))

  
